version: '3.1'

services:

  web:
    build: .
    ports:
      - "8042:80"
    volumes:
      - ./solutions/A05/flag.txt:/etc/flag_xxe.txt:ro
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vulnerable_app
    volumes:
      - db_data:/var/lib/mysql
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql

  nexus_server:
   image: sonatype/nexus3:3.14.0
   ports:
    - "8081:8081"
   volumes:
      - ./solutions/A06/flag.txt:/etc/flag.txt:ro

volumes:
  db_data: