version: '3.1'

services:

  web:
    build: .
    ports:
      - "8042:80"
    depends_on:
      - db

  vulnerable:
    image: vulnerables/cve-2016-10033
    ports:
      - "8084:80"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vulnerable_app
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: